import type { AmbientCloudPlacement } from '../types';

/**
 * Фон-небо сцены (`SkyAmbientBackdrop`): градиент `--gradient-sky-backdrop` и мягкие облака.
 * Тайминги и раскладка общие для всех сцен, в которых он есть, — своих копий у сцен нет.
 */

/** Облака на небе плавно проявляются и гаснут по пропу `visible`, мс. */
export const AMBIENT_CLOUD_FADE_MS = 1200;

/** Самый короткий полупериод медленного дрейфа облака (туда или обратно), мс. */
export const AMBIENT_CLOUD_MIN_DRIFT_MS = 22000;

/**
 * Самый длинный полупериод дрейфа, мс. У каждого облака свой полупериод в диапазоне
 * от `AMBIENT_CLOUD_MIN_DRIFT_MS` до этого значения — облака не идут в такт.
 */
export const AMBIENT_CLOUD_MAX_DRIFT_MS = 33000;

/**
 * Раскладка облаков по всему небу, в порядке наложения (последнее — ближе к зрителю):
 * дальние — мелкие и бледные, заполняют просветы; средние — вокруг главного предмета сцены
 * (дека, торт) и за ним; ближние — крупные, обрамляют кадр по краям и в углах.
 * Небо между облаками просвечивает. Координаты — доли экрана.
 */
export const SKY_AMBIENT_CLOUDS: readonly AmbientCloudPlacement[] = [
  // Дальние: мелкие, бледные, дрейфуют едва заметно.
  {
    id: 'far-top-left',
    image: 'cloud-05',
    leftVw: 18,
    topVh: 12,
    widthVw: 16,
    flipped: true,
    opacity: 0.45,
    driftVw: 1.5,
  },
  {
    id: 'far-top-right',
    image: 'cloud-01',
    leftVw: 60,
    topVh: 11,
    widthVw: 18,
    flipped: true,
    opacity: 0.45,
    driftVw: -1.5,
  },
  {
    id: 'far-corner-right',
    image: 'cloud-03',
    leftVw: 84,
    topVh: -4,
    widthVw: 20,
    flipped: false,
    opacity: 0.5,
    driftVw: -2,
  },
  {
    id: 'far-left',
    image: 'cloud-01',
    leftVw: 2,
    topVh: 30,
    widthVw: 20,
    flipped: false,
    opacity: 0.5,
    driftVw: 2,
  },
  {
    id: 'far-right',
    image: 'cloud-05',
    leftVw: 84,
    topVh: 62,
    widthVw: 18,
    flipped: true,
    opacity: 0.5,
    driftVw: -2,
  },
  {
    id: 'far-top-middle',
    image: 'cloud-04',
    leftVw: 28,
    topVh: 2,
    widthVw: 14,
    flipped: false,
    opacity: 0.4,
    driftVw: 1.2,
  },
  {
    id: 'far-inner-right',
    image: 'cloud-03',
    leftVw: 64,
    topVh: 26,
    widthVw: 15,
    flipped: true,
    opacity: 0.4,
    driftVw: -1.2,
  },
  {
    id: 'far-inner-left',
    image: 'cloud-02',
    leftVw: 20,
    topVh: 34,
    widthVw: 15,
    flipped: false,
    opacity: 0.4,
    driftVw: 1.2,
  },
  {
    id: 'far-right-edge',
    image: 'cloud-04',
    leftVw: 90,
    topVh: 30,
    widthVw: 14,
    flipped: true,
    opacity: 0.45,
    driftVw: -1.5,
  },
  {
    id: 'far-left-edge',
    image: 'cloud-05',
    leftVw: -2,
    topVh: 58,
    widthVw: 14,
    flipped: false,
    opacity: 0.45,
    driftVw: 1.5,
  },
  {
    id: 'far-bottom-right',
    image: 'cloud-01',
    leftVw: 74,
    topVh: 86,
    widthVw: 16,
    flipped: true,
    opacity: 0.45,
    driftVw: -1.5,
  },
  {
    id: 'far-bottom-left',
    image: 'cloud-03',
    leftVw: 22,
    topVh: 88,
    widthVw: 16,
    flipped: false,
    opacity: 0.45,
    driftVw: 1.5,
  },
  // Средние: вокруг главного предмета сцены и за ним.
  {
    id: 'ambient-high-center',
    image: 'cloud-03',
    leftVw: 36,
    topVh: -6,
    widthVw: 28,
    flipped: false,
    opacity: 0.55,
    driftVw: 2,
  },
  {
    id: 'inner-left',
    image: 'cloud-02',
    leftVw: 15,
    topVh: 50,
    widthVw: 24,
    flipped: false,
    opacity: 0.55,
    driftVw: 2,
  },
  {
    id: 'inner-right',
    image: 'cloud-05',
    leftVw: 62,
    topVh: 54,
    widthVw: 24,
    flipped: true,
    opacity: 0.55,
    driftVw: -2,
  },
  {
    id: 'ambient-middle-left',
    image: 'cloud-05',
    leftVw: -10,
    topVh: 40,
    widthVw: 34,
    flipped: false,
    opacity: 0.65,
    driftVw: 2.5,
  },
  {
    id: 'ambient-middle-right',
    image: 'cloud-03',
    leftVw: 76,
    topVh: 38,
    widthVw: 32,
    flipped: true,
    opacity: 0.65,
    driftVw: -2.5,
  },
  {
    id: 'inner-top-left',
    image: 'cloud-04',
    leftVw: 10,
    topVh: 14,
    widthVw: 22,
    flipped: true,
    opacity: 0.55,
    driftVw: 1.8,
  },
  {
    id: 'inner-top-right',
    image: 'cloud-01',
    leftVw: 64,
    topVh: 16,
    widthVw: 22,
    flipped: false,
    opacity: 0.55,
    driftVw: -1.8,
  },
  {
    id: 'inner-bottom-left',
    image: 'cloud-03',
    leftVw: 22,
    topVh: 66,
    widthVw: 22,
    flipped: true,
    opacity: 0.6,
    driftVw: 2,
  },
  {
    id: 'inner-bottom-right',
    image: 'cloud-02',
    leftVw: 58,
    topVh: 68,
    widthVw: 22,
    flipped: false,
    opacity: 0.6,
    driftVw: -2,
  },
  // Ближние: крупные, обрамляют кадр по краям и в углах.
  {
    id: 'ambient-top-left',
    image: 'cloud-02',
    leftVw: -6,
    topVh: 2,
    widthVw: 34,
    flipped: false,
    opacity: 0.75,
    driftVw: 3,
  },
  {
    id: 'ambient-top-right',
    image: 'cloud-04',
    leftVw: 70,
    topVh: 5,
    widthVw: 36,
    flipped: true,
    opacity: 0.7,
    driftVw: -3,
  },
  {
    id: 'near-top-center',
    image: 'cloud-01',
    leftVw: 50,
    topVh: -10,
    widthVw: 30,
    flipped: true,
    opacity: 0.7,
    driftVw: -2,
  },
  {
    id: 'near-left-edge',
    image: 'cloud-03',
    leftVw: -14,
    topVh: 18,
    widthVw: 26,
    flipped: false,
    opacity: 0.75,
    driftVw: 2.5,
  },
  {
    id: 'near-right-edge',
    image: 'cloud-05',
    leftVw: 88,
    topVh: 44,
    widthVw: 26,
    flipped: true,
    opacity: 0.75,
    driftVw: -2.5,
  },
  {
    id: 'bottom-center',
    image: 'cloud-04',
    leftVw: 34,
    topVh: 84,
    widthVw: 30,
    flipped: false,
    opacity: 0.7,
    driftVw: 2,
  },
  {
    id: 'ambient-bottom-left',
    image: 'cloud-01',
    leftVw: 2,
    topVh: 72,
    widthVw: 40,
    flipped: false,
    opacity: 0.8,
    driftVw: 3,
  },
  {
    id: 'ambient-bottom-right',
    image: 'cloud-02',
    leftVw: 56,
    topVh: 74,
    widthVw: 44,
    flipped: true,
    opacity: 0.8,
    driftVw: -3,
  },
  {
    id: 'near-bottom-left-corner',
    image: 'cloud-05',
    leftVw: -12,
    topVh: 84,
    widthVw: 30,
    flipped: false,
    opacity: 0.8,
    driftVw: 2,
  },
  {
    id: 'near-bottom-right-corner',
    image: 'cloud-03',
    leftVw: 86,
    topVh: 80,
    widthVw: 28,
    flipped: true,
    opacity: 0.8,
    driftVw: -2,
  },
];
