import type { ComicPage } from '../types';
import { assetUrl } from '../utils/assetUrl';
import { ASSET_DIRECTORIES } from './assets';

/**
 * Страницы комикса из `public/assets/comic/` по порядку чтения — их показывает модалка
 * «Книга» (`ComicReader`).
 *
 * Имена файлов перечислены как есть, расширения у страниц разные. Чтобы добавить,
 * убрать или переставить страницу, правьте только этот список: номер страницы в счётчике
 * берётся из позиции в нём, а не из имени файла.
 */
const PAGE_FILES = [
  '0.jpg',
  '1.jpeg',
  '2.jpeg',
  '3.jpeg',
  '4.jpeg',
  '5.jpg',
  '6.jpg',
  '7.jpg',
  '8.jpeg',
  '9.jpeg',
  '10.jpg',
  '11.jpg',
  '12.jpeg',
  '13.jpeg',
  '14.jpeg',
  '15.jpeg',
  '16.jpg',
  '17.jpeg',
  '18.jpg',
  '19.jpg',
  '20.jpeg',
  '21.jpeg',
  '22.jpeg',
  '23.jpeg',
  '24.jpeg',
  '25.png',
  '26.jpg',
  '27.jpeg',
  '28.jpeg',
  '29.jpeg',
  '30.jpg',
  '31.jpeg',
  '32.jpeg',
  '33.jpeg',
  '34.jpeg',
  '35.jpeg',
  '36.jpeg',
  '37.jpg',
  '38.jpg',
  '39.jpeg',
  '40.jpg',
  '41.jpg',
  '42.jpg',
  '43.jpg',
  '44.jpg',
  '45.jpg',
  '46.jpg',
  '47.jpg',
  '48.jpg',
  '49.jpg',
  '50.jpg',
  '51.jpg',
  '52.jpg',
  '53.jpg',
  '54.jpg',
  '55.jpg',
  '56.jpg',
  '57.jpg',
  '58.jpg',
  '59.jpg',
  '60.jpg',
  '61.jpg',
  '62.jpg',
  '63.jpg',
  '64.jpg',
  '65.jpg',
  '66.jpg',
  '67.jpg',
  '68.jpg',
  '69.jpg',
  '70.jpg',
  '71.jpg',
  '72.jpg',
  '73.jpg',
  '74.jpg',
  '76.jpg',
  '77.jpg',
  '78.jpg',
  '79.jpg',
  '80.jpg',
  '81.jpg',
  '82.jpg',
  '83.jpg',
  '84.jpg',
  '85.jpeg',
  '86.jpeg',
  '87.png',
  '88.jpeg',
  '89.jpeg',
  '90.jpeg',
] as const;

/** Страницы комикса по порядку чтения. */
export const COMIC_PAGES: readonly ComicPage[] = PAGE_FILES.map((file) => ({
  id: file,
  src: assetUrl(`${ASSET_DIRECTORIES.comic}/${file}`),
}));
